# -*- coding: utf-8 -*-
"""3-1 SDC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wgOt3YH9LC9AtWNyI0JGcwlg-_7Kir6A

steps for Data Cleaning

1.import the libraries-pandas,numpy,Seabon

2.Read the Dataset by intializing
  file format :csv,tsv,excel

3.Find the Null Values

4.Handling Null Values

5.Find the Categorical values

6.Handling Categorical values

7.Feature Extraction using Co-relation and co-variants

8.split independent and dependents

9.train test split

**iris**
"""

import pandas as pd
import numpy as np
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

data=pd.read_csv('/IRIS.csv')

data.info()

"""**above species are categorical values because it is object**"""

data.isnull()

data.head()

data.sample(10)

data.columns

data.shape

print(data)

specific_data=data["species"]
print(specific_data.head(10))

data.iloc[5]

data.loc[data["species"] == "Iris-setosa"]

data["species"].value_counts()

x=data.drop(['species'],axis=1)
y=pd.DataFrame(data['species'])

min_data=data["sepal_length"].min()
max_data=data["sepal_length"].max()

print("Minimum:",min_data, "\nMaximum:", max_data)

data.species.unique()

sum_data = data["sepal_length"].sum()
mean_data = data["sepal_length"].mean()
median_data = data["sepal_length"].median()

print("Sum:",sum_data, "\nMean:", mean_data, "\nMedian:",median_data)

"""**handling categorical values**"""

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

data.species=le.fit_transform(data.species)

data.info()

data.species.unique()

data.corr()

x=data.drop(['species'],axis=1)
y=pd.DataFrame(data['species'])

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

sns.pairplot(data)

