# -*- coding: utf-8 -*-
"""EX_5_PANDAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yjyXrVG5joNjEodmBW3HJC0y5c9Rrtnk

***AIM:Create a IPython Module To Work With Pandas:Series and DataFrame  ***

**Creating a Series**
"""

import pandas as pd
import numpy as np
numbers=[10,20,30,40,50]
labels=['A','B','C','D','E']
ser=pd.Series(data=numbers,index=labels)

ser

type(ser)

ser1=pd.Series(np.arange(5,10))#if we doesnt specify  the index it will take default values like array
ser1

ser2=pd.Series(np.arange(5,10),['a','b','c','d','e'])
ser2

"""# **Creating series from dictionary**"""

import pandas as pd
ser4=pd.Series({'A':65,'B':66,'C':67,'D':68})
print(ser4)

myd={'a':97,'b':98,'c':99,'d':100}#creating series from dictionary

ser3=pd.Series(myd)
ser3

ser4=pd.Series(myd,name="ASCII")
ser4

#Accessing elements in series
ser[1]

ser4['b']

ser5=pd.Series(np.arange(15,23),'a b c d e f g h'.split())
ser5

print('a b c d e f g h'.split())

"""**Slicing**"""

ser5[['a','b','c']]#Fancy Indexing

ser5[:3]#slicing

ser5[['f','e','c']]#Fancy Indexing

ser5>13#boolean Indexing

ser5>18

ser5[ser5>19]#we will get only greater than values that is true----   Boolean Indexing

ser1

#to change the index
ser1.reindex(['p','q','r','s','t'],)

"""**Create a DataFrame**"""

df=pd.DataFrame(data=np.random.randint(1,20,size=(4,3)),index=['A','B','C','D'],columns=['W','x','Y'])
df

df

df['W']#Accessing column

#to access the row
df.loc['A']

df

df.iloc[2]#index location (Or)Normal Indexing

df.W#to Access column

df['Z']=df['W']+df['Y']
df

#with respect to to columns retieve sub dataframe
df[['W','Z']]

df[['W','Z']].loc[['A','C','D']]#to access paricular rows

#wrt to rows retieve sub dataframe
df.loc[['A','D']]

df.loc[['A','D']][['x','Y']]

df['W']['B']

df6=pd.DataFrame(data=np.random.randint(1,20,size=(5,3)),index=['A','B','C','D','E'],columns=['W','x','Y'])
df6

c