# -*- coding: utf-8 -*-
"""irisml.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yOiXWEg9tLoOEzZIjZJfPRfmTfbjNan-

**steps for Data Cleaning

1.import the libraries-pandas,numpy,Seabon

2.Read the Dataset by intializing
  file format :csv,tsv,excel

3.Find the Null Values

4.Handling Null Values

5.Find the Categorical values

6.Handling Categorical values

7.Feature Extraction using Co-relation and co-variants

8.split independent and dependents

9.train test split**
"""

import numpy as np
import pandas as pd
import seaborn as sns

data=pd.read_csv('/IRIS.csv')

data.info()

data.isnull()

"""# New Section"""

data.head()

"""**handling categorical values**"""

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['species']=le.fit_transform(data['species'])

data.cov

data.corr

"""**seperating dependent and independent variables**"""

x=data.drop(['species'],axis=1)
y=pd.DataFrame(data['species'])

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

sns.pairplot(data,hue="species")

from sklearn.linear_model import LogisticRegression

lr=LogisticRegression(max_iter=1000)
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

from sklearn.metrics import accuracy_score

from google.colab import drive
drive.mount('/content/drive')

accuracy_score(y_test,y_pred)

import pickle as pkl

pkl.dump(lr,open('IRIS.pkl','wb'))

import pickle as pkl
pklf1=pkl.load(open('/content/IRIS.pkl','rb'))

a=pklf1.predict

sl=float(input("enter seapl length"))
sw=float(input("enter seapl width"))
pl=float(input("enter petal length"))
pw=float(input("enter petal width"))
z=pklf1.predict([[sl,sw,pl,pw]])
if z[0]==0:
  print("setaso iris flower")
elif z[0]==1:
  print("versicolor iris flower")
else:
  print("virginica iris flower")

